"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]

success_symbol = '[➜](bold green)' 

[aws]
symbol = "  "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[os.symbols]
Macos = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "

