eval "$(starship init zsh)"

# PLUGINS
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/kubectl.plugin.zsh

# HISTORY
HISTSIZE=1000   # Number of commands to keep in memory
SAVEHIST=1000000  # Number of commands to save in the history file
HISTFILE=~/.zsh/my_custom_history
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt EXTENDED_HISTORY

# Set the default editor
export EDITOR="emacs"

# Set the default browser
export BROWSER="brave"

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# GO PATH
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# BREW PATH
eval "$(/opt/homebrew/bin/brew shellenv)"
